"""
Memory consolidation engine for NeuroMem.

Handles the promotion of episodic memories to semantic/procedural memory,
mimicking the hippocampus-to-neocortex consolidation process in the brain.
"""

import uuid
from datetime import datetime, timezone
from typing import List, Dict
from neuromem.core.types import MemoryItem, MemoryType, ConsolidationResult
from neuromem.memory.consolidation import ConsolidationEngine


class Consolidator:
    """
    Consolidates episodic memories into semantic and procedural memories.

    This mimics the brain's process of:
    1. Identifying repeated patterns in episodic memory
    2. Extracting stable facts (semantic)
    3. Learning behavioral patterns (procedural)
    4. Discarding or decaying unreinforced memories
    """

    def __init__(self, llm_model: str = "gpt-4o-mini", config: Dict = None):
        """
        Initialize the consolidator.

        Args:
            llm_model: LLM model to use for consolidation
            config: Configuration dictionary
        """
        self.llm_model = llm_model

        # Initialize the actual engine
        min_confidence = 0.7
        if config and "consolidation" in config:
            min_confidence = config["consolidation"].get("min_confidence", 0.7)

        self.engine = ConsolidationEngine(llm_model=llm_model, min_confidence=min_confidence)

        self.config = config or {}

    def consolidate(
        self,
        episodic_items: List[MemoryItem],
        existing_semantic: List[MemoryItem],
        existing_procedural: List[MemoryItem],
    ) -> ConsolidationResult:
        """
        Perform memory consolidation.

        Args:
            episodic_items: Episodic memories to consolidate
            existing_semantic: Existing semantic memories
            existing_procedural: Existing procedural memories

        Returns:
            ConsolidationResult with promoted and decayed memories
        """
        result = ConsolidationResult(promoted_count=0, decayed_count=0, merged_count=0)

        if not episodic_items:
            return result

        # Get consolidation settings
        cons_config = self.config.get("consolidation", {})
        extract_facts = cons_config.get("extract_facts", True)
        create_summaries = cons_config.get("create_summaries", True)
        apply_forgetting = cons_config.get("apply_forgetting", True)

        # Run consolidation engine
        engine_results = self.engine.consolidate_batch(
            episodic_memories=episodic_items,
            extract_facts=extract_facts,
            create_summaries=create_summaries,
            apply_forgetting=apply_forgetting,
        )

        # Process extracted facts -> Semantic Memories
        for fact in engine_results.get("facts_extracted", []):
            semantic_mem = MemoryItem(
                id=str(uuid.uuid4()),
                user_id=episodic_items[0].user_id,
                content=fact["fact"],
                embedding=[],  # Will be generated by controller
                memory_type=MemoryType.SEMANTIC,
                salience=0.8,
                confidence=fact.get("confidence", 0.8),
                created_at=datetime.now(timezone.utc),
                last_accessed=datetime.now(timezone.utc),
                decay_rate=0.01,
                reinforcement=1,
                inferred=True,
                editable=True,
                tags=fact.get("tags", []) + ["consolidated"],
                metadata={
                    "fact_type": fact.get("fact_type"),
                    "source_ids": fact.get("source_memory_ids"),
                },
            )
            result.new_semantic_memories.append(semantic_mem)
            result.promoted_count += 1

        # Process summaries -> Procedural Memories (or specialized episodic summaries)
        # For now, we store summaries as high-level episodic memories marked as 'summary'
        # or procedural if they look like patterns
        for summary in engine_results.get("summaries_created", []):
            # Create a summary memory item
            summary_mem = MemoryItem(
                id=str(uuid.uuid4()),
                user_id=episodic_items[0].user_id,
                content=f"Conversation Summary: {summary['summary']}",
                embedding=[],  # Will be generated by controller
                memory_type=MemoryType.SEMANTIC,
                salience=summary.get("salience", 0.5),
                confidence=1.0,
                created_at=datetime.now(timezone.utc),
                last_accessed=datetime.now(timezone.utc),
                decay_rate=0.02,
                reinforcement=1,
                inferred=True,
                editable=True,
                tags=summary.get("topic_tags", []) + ["summary"],
                metadata={
                    "key_points": summary.get("key_points", []),
                    "message_count": summary.get("message_count"),
                },
            )
            # Add to semantic for now so it gets stored in long-term memory
            result.new_semantic_memories.append(summary_mem)
            result.promoted_count += 1

        return result
